"""add support wallet

Revision ID: 2c3840a02c19
Revises: c1ca4b4e31d7
Create Date: 2026-01-20 01:30:50.190729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c3840a02c19'
down_revision: Union[str, Sequence[str], None] = 'c1ca4b4e31d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('support_wallet', sa.String(length=42), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'support_wallet')
    # ### end Alembic commands ###
