"""add vibe description

Revision ID: f6c81adfcb29
Revises: 2c3840a02c19
Create Date: 2026-01-24 17:51:02.614187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c81adfcb29'
down_revision: Union[str, Sequence[str], None] = '2c3840a02c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('vibe_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'vibe_description')
    # ### end Alembic commands ###
